const lessonTitle = "尘埃";

const lessonData = [
    // ===== 第1段 =====
    ["灰尘", "huī chén", "dust", "habuk"],
    ["是", "shì", "is", "ialah"],
    ["人人", "rén rén", "everyone", "semua orang"],
    ["讨厌", "tǎo yàn", "dislike", "benci"],
    ["的", "de", "", ""],
    ["东西", "dōng xi", "thing", "benda"],
    ["。", "", "", ""],
    ["它", "tā", "It", "Ia"],
    ["污染", "wū rǎn", "pollutes", "mencemarkan"],
    ["空气", "kōng qì", "air", "udara"],
    ["，", "", "", ""],
    ["传播", "chuán bō", "spreads", "menyebarkan"],
    ["疾病", "jí bìng", "diseases", "penyakit"],
    ["，", "", "", ""],
    ["危害", "wēi hài", "harms", "membahayakan"],
    ["人类", "rén lèi", "human", "manusia"],
    ["的", "de", "", ""],
    ["健康", "jiàn kāng", "health", "kesihatan"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "Therefore", "Maka"],
    ["，", "", "", ""],
    ["古往今来", "gǔ wǎng jīn lái", "throughout the ages", "sejak dahulu hingga kini"],
    ["，", "", "", ""],
    ["人们", "rén men", "people", "orang ramai"],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["“", "", "", ""],
    ["时时勤拂拭", "shí shí qín fú shì", "always wipe it clean", "sentiasa membersihkan"],
    ["，", "", "", ""],
    ["勿使惹尘埃", "wù shǐ rě chén āi", "don't let it get dusty", "jangan biarkan berhabuk"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["然而", "rán ér", "However", "Namun"],
    ["，", "", "", ""],
    ["你可曾想到", "nǐ kě céng xiǎng dào", "have you ever thought", "pernahkah awak terfikir"],
    ["，", "", "", ""],
    ["人类", "rén lèi", "human", "manusia"],
    ["的", "de", "", ""],
    ["生息", "shēng xī", "existence and survival", "kehidupan"],
    ["离不开", "lí bù kāi", "cannot do without", "tidak dapat dipisahkan"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["灰尘颗粒", "huī chén kē lì", "Dust particles", "Partikel habuk"],
    ["的", "de", "", ""],
    ["直径", "zhí jìng", "diameter", "diameter"],
    ["虽然", "suī rán", "although", "walaupun"],
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["万分之一毫米", "wàn fēn zhī yī háo mǐ", "one ten-thousandth of a millimeter", "sepersejuta milimeter"],
    ["到", "dào", "to", "hingga"],
    ["几百分之一毫米", "jǐ bǎi fēn zhī yī háo mǐ", "one several-hundredth of a millimeter", "beberapa perseratus milimeter"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["它", "tā", "it", "ia"],
    ["却有", "què yǒu", "has", "mempunyai"],
    ["固有的", "gù yǒu de", "inherent", "semula jadi"],
    ["物理特性", "wù lǐ tè xìng", "physical properties", "sifat fizikal"],
    ["：", "", "", ""],
    ["灰尘", "huī chén", "Dust", "Habuk"],
    ["不仅", "bù jǐn", "not only", "bukan sahaja"],
    ["会", "huì", "can", "boleh"],
    ["散射", "sǎn shè", "scatter", "menyerakkan"],
    ["光线", "guāng xiàn", "light", "cahaya"],
    ["，", "", "", ""],
    ["而且", "ér qiě", "and also", "dan juga"],
    ["它具有", "tā jù yǒu", "it has", "ia mempunyai"],
    ["吸湿性", "xī shī xìng", "hygroscopicity", "sifat menyerap lembapan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["假如", "jiǎ rú", "If", "Sekiranya"],
    ["大气中", "dà qì zhōng", "in the atmosphere", "di atmosfera"],
    ["没有", "méi yǒu", "there is no", "tiada"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["，", "", "", ""],
    ["大自然", "dà zì rán", "nature", "alam semula jadi"],
    ["将是", "jiāng shì", "would be", "akan menjadi"],
    ["另一番景象", "lìng yī fān jǐng xiàng", "a different scene", "pemandangan yang berbeza"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["阳光", "yáng guāng", "Sunlight", "Cahaya matahari"],
    ["经过", "jīng guò", "after passing through", "selepas melalui"],
    ["大气", "dà qì", "the atmosphere", "atmosfera"],
    ["的", "de", "", ""],
    ["散射", "sǎn shè", "scattering", "serakan"],
    ["，", "", "", ""],
    ["才能", "cái néng", "can", "baru boleh"],
    ["变得", "biàn de", "become", "menjadi"],
    ["柔和", "róu hé", "soft", "lembut"],
    ["。", "", "", ""],
    ["假如", "jiǎ rú", "If", "Sekiranya"],
    ["大气中", "dà qì zhōng", "in the atmosphere", "di atmosfera"],
    ["没有", "méi yǒu", "there is no", "tiada"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["，", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["将", "jiāng", "would", "akan"],
    ["直接", "zhí jiē", "directly", "secara langsung"],
    ["照射", "zhào shè", "shine", "menyinari"],
    ["在", "zài", "on", "di"],
    ["地球上", "dì qiú shàng", "the Earth", "bumi"],
    ["，", "", "", ""],
    ["那么", "nà me", "then", "maka"],
    ["，", "", "", ""],
    ["由于", "yóu yú", "because", "kerana"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["的", "de", "", ""],
    ["散射", "sǎn shè", "scattering", "serakan"],
    ["，", "", "", ""],
    ["即便", "jí biàn", "even", "walaupun"],
    ["在", "zài", "in", "pada"],
    ["阳光灿烂", "yáng guāng càn làn", "sunny", "cerah"],
    ["的", "de", "", ""],
    ["白天", "bái tiān", "daytime", "siang hari"],
    ["，", "", "", ""],
    ["天空", "tiān kōng", "the sky", "langit"],
    ["也将", "yě jiāng", "would also", "juga akan"],
    ["是", "shì", "be", "ialah"],
    ["黑洞洞的", "hēi dòng dòng de", "pitch black", "gelap gelita"],
    ["，", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["在", "zài", "in", "pada"],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["直接", "zhí jiē", "directly", "secara langsung"],
    ["照射", "zhào shè", "shining", "menyinari"],
    ["的", "de", "", ""],
    ["地方", "dì fang", "places", "tempat-tempat"],
    ["，", "", "", ""],
    ["则会", "zé huì", "would", "akan"],
    ["由于", "yóu yú", "because", "kerana"],
    ["光线太强", "guāng xiàn tài qiáng", "light is too strong", "cahaya terlalu kuat"],
    ["，", "", "", ""],
    ["使人", "shǐ rén", "make people", "membuatkan orang"],
    ["无法", "wú fǎ", "unable to", "tidak dapat"],
    ["睁开眼睛", "zhēng kāi yǎn jīng", "open their eyes", "membuka mata"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["阳光中", "yáng guāng zhōng", "In sunlight", "Dalam cahaya matahari"],
    ["的", "de", "", ""],
    ["短波光线", "duǎn bō guāng xiàn", "short-wave light", "cahaya gelombang pendek"],
    ["（", "", "", ""],
    ["如", "rú", "such as", "seperti"],
    ["蓝光", "lán guāng", "blue light", "cahaya biru"],
    ["、", "", "", ""],
    ["青光", "qīng guāng", "cyan light", "cahaya sian"],
    ["、", "", "", ""],
    ["紫光", "zǐ guāng", "violet light", "cahaya ungu"],
    ["）", "", "", ""],
    ["比", "bǐ", "than", "daripada"],
    ["长波光线", "cháng bō guāng xiàn", "long-wave light", "cahaya gelombang panjang"],
    ["（", "", "", ""],
    ["如", "rú", "such as", "seperti"],
    ["红光", "hóng guāng", "red light", "cahaya merah"],
    ["、", "", "", ""],
    ["橙光", "chéng guāng", "orange light", "cahaya oren"],
    ["）", "", "", ""],
    ["容易被", "róng yì bèi", "are more easily", "lebih mudah"],
    ["大气中", "dà qì zhōng", "in the atmosphere", "di atmosfera"],
    ["的", "de", "", ""],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["散射", "sǎn shè", "scattered", "diserakkan"],
    ["。", "", "", ""],
    ["由于", "yóu yú", "Because", "Kerana"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["对", "duì", "to", "terhadap"],
    ["阳光中", "yáng guāng zhōng", "sunlight's", "cahaya matahari punya"],
    ["短波光线的", "duǎn bō guāng xiàn de", "short-wave light", "cahaya gelombang pendek"],
    ["散射作用", "sǎn shè zuò yòng", "scattering effect", "kesan serakan"],
    ["，", "", "", ""],
    ["才", "cái", "only then", "baru"],
    ["使", "shǐ", "makes", "menjadikan"],
    ["天空", "tiān kōng", "the sky", "langit"],
    ["呈现出", "chéng xiàn chū", "appear", "menjadi"],
    ["蔚蓝色", "wèi lán sè", "azure blue", "biru langit"],
    ["。", "", "", ""],
    ["假如", "jiǎ rú", "If", "Sekiranya"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["，", "", "", ""],
    ["天空", "tiān kōng", "the sky", "langit"],
    ["将", "jiāng", "would", "akan"],
    ["不是", "bú shì", "not be", "bukan"],
    ["蔚蓝色的了", "wèi lán sè de le", "azure blue", "biru langit"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["灰尘", "huī chén", "Dust", "Habuk"],
    ["还是", "hái shì", "is also", "juga"],
    ["天然的", "tiān rán de", "natural", "semula jadi"],
    ["“", "", "", ""],
    ["吸湿剂", "xī shī jì", "hygroscopic agent", "agen penyerap lembapan"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["如果", "rú guǒ", "If", "Jika"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["，", "", "", ""],
    ["空气中", "kōng qì zhōng", "in the air", "di udara"],
    ["的", "de", "", ""],
    ["水蒸气", "shuǐ zhēng qì", "water vapor", "wap air"],
    ["就", "jiù", "then", "maka"],
    ["无法", "wú fǎ", "cannot", "tidak dapat"],
    ["凝结", "níng jié", "condense", "memeluwap"],
    ["。", "", "", ""],
    ["在", "zài", "In", "Dalam"],
    ["大气中", "dà qì zhōng", "the atmosphere", "atmosfera"],
    ["，", "", "", ""],
    ["正是", "zhèng shì", "it is precisely", "itulah"],
    ["由于", "yóu yú", "because", "kerana"],
    ["有", "yǒu", "there is", "ada"],
    ["了", "le", "", ""],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["作为", "zuò wéi", "as", "sebagai"],
    ["核心", "hé xīn", "core", "teras"],
    ["，", "", "", ""],
    ["水蒸气", "shuǐ zhēng qì", "water vapor", "wap air"],
    ["才能", "cái néng", "can", "baru boleh"],
    ["凝结成", "níng jié chéng", "condense into", "memeluwap menjadi"],
    ["无数", "wú shù", "countless", "tidak terhitung"],
    ["的", "de", "", ""],
    ["小水滴", "xiǎo shuǐ dī", "small water droplets", "titisan air kecil"],
    ["，", "", "", ""],
    ["从而", "cóng ér", "thus", "lantas"],
    ["形成", "xíng chéng", "form", "membentuk"],
    ["云", "yún", "clouds", "awan"],
    ["。", "", "", ""],
    ["如果", "rú guǒ", "If", "Jika"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["云", "yún", "clouds", "awan"],
    ["，", "", "", ""],
    ["也就", "yě jiù", "then there would be no", "maka tiada"],
    ["没有", "méi yǒu", "", ""],
    ["雨", "yǔ", "rain", "hujan"],
    ["和", "hé", "and", "dan"],
    ["雪", "xuě", "snow", "salji"],
    ["，", "", "", ""],
    ["地面上", "dì miàn shàng", "on the ground", "di permukaan bumi"],
    ["的", "de", "", ""],
    ["生物", "shēng wù", "living things", "makhluk hidup"],
    ["也将", "yě jiāng", "would also", "juga akan"],
    ["无法", "wú fǎ", "unable to", "tidak dapat"],
    ["生存", "shēng cún", "survive", "bertahan hidup"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["此外", "cǐ wài", "In addition", "Selain itu"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["，", "", "", ""],
    ["不仅", "bù jǐn", "not only", "bukan sahaja"],
    ["不会", "bú huì", "there would be no", "tidak akan ada"],
    ["有", "yǒu", "", ""],
    ["云", "yún", "clouds", "awan"],
    ["，", "", "", ""],
    ["而且", "ér qiě", "and also", "dan juga"],
    ["即便", "jí biàn", "even if", "walaupun"],
    ["空气中", "kōng qì zhōng", "in the air", "di udara"],
    ["的", "de", "", ""],
    ["水蒸气", "shuǐ zhēng qì", "water vapor", "wap air"],
    ["达到", "dá dào", "reaches", "mencapai"],
    ["饱和状态", "bǎo hé zhuàng tài", "saturation", "keadaan tepu"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["不会", "bú huì", "would not", "tidak akan"],
    ["凝结成", "níng jié chéng", "condense into", "memeluwap menjadi"],
    ["雾", "wù", "fog", "kabut"],
    ["，", "", "", ""],
    ["更不会", "gèng bú huì", "let alone", "apatah lagi"],
    ["形成", "xíng chéng", "form", "membentuk"],
    ["晚霞", "wǎn xiá", "sunset glow", "awan senja"],
    ["、", "", "", ""],
    ["朝霞", "zhāo xiá", "sunrise glow", "awan subuh"],
    ["、", "", "", ""],
    ["彩虹", "cǎi hóng", "rainbow", "pelangi"],
    ["和", "hé", "and", "dan"],
    ["绚丽的", "xuàn lì de", "splendid", "indah"],
    ["日落景观", "rì luò jǐng guān", "sunset scenery", "pemandangan matahari terbenam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["由此可见", "yóu cǐ kě jiàn", "Thus it can be seen", "Dengan ini dapat dilihat"],
    ["，", "", "", ""],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["虽然", "suī rán", "although", "walaupun"],
    ["令人讨厌", "lìng rén tǎo yàn", "annoying", "menjengkelkan"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["它", "tā", "it", "ia"],
    ["在", "zài", "in", "dalam"],
    ["自然界中", "zì rán jiè zhōng", "nature", "alam semula jadi"],
    ["也是", "yě shì", "is also", "juga"],
    ["不可缺少的", "bù kě quē shǎo de", "indispensable", "tidak boleh dipisahkan"],
    ["。", "", "", ""],
    ["如果", "rú guǒ", "If", "Jika"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["灰尘", "huī chén", "dust", "habuk"],
    ["，", "", "", ""],
    ["不仅", "bù jǐn", "not only", "bukan sahaja"],
    ["大自然", "dà zì rán", "nature", "alam semula jadi"],
    ["会失去", "huì shī qù", "would lose", "akan kehilangan"],
    ["很多", "hěn duō", "many", "banyak"],
    ["美妙的奇观", "měi miào de qí guān", "wonderful wonders", "pemandangan yang indah"],
    ["，", "", "", ""],
    ["连", "lián", "even", "malahan"],
    ["人类", "rén lèi", "humanity", "manusia"],
    ["也无法生存了", "yě wú fǎ shēng cún le", "could not survive", "tidak dapat bertahan hidup"],
    ["。", "", "", ""],
    ["当然", "dāng rán", "Of course", "Tentu"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika"],
    ["大气中", "dà qì zhōng", "in the atmosphere", "di atmosfera"],
    ["灰尘过多", "huī chén guò duō", "there is too much dust", "terlalu banyak habuk"],
    ["，", "", "", ""],
    ["也会", "yě huì", "will also", "juga akan"],
    ["给人类", "gěi rén lèi", "bring to humanity", "memberi kepada manusia"],
    ["带来危害", "dài lái wēi hài", "bring harm", "mendatangkan bahaya"],
    ["。", "", "", ""],
    ["因此", "yīn cǐ", "Therefore", "Maka"],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kita"],
    ["应该", "yīng gāi", "should", "patut"],
    ["通过各种手段", "tōng guò gè zhǒng shǒu duàn", "through various means", "melalui pelbagai cara"],
    ["，", "", "", ""],
    ["使", "shǐ", "keep", "mengekalkan"],
    ["大气中", "dà qì zhōng", "in the atmosphere", "di atmosfera"],
    ["的灰尘", "de huī chén", "dust", "habuk"],
    ["保持", "bǎo chí", "maintain", "mengekalkan"],
    ["在", "zài", "at", "pada"],
    ["一定的程度", "yí dìng de chéng dù", "a certain level", "tahap tertentu"],
    ["，", "", "", ""],
    ["这才", "zhè cái", "this is", "inilah"],
    ["是", "shì", "is", "ialah"],
    ["科学的", "kē xué de", "scientific", "saintifik"],
    ["态度", "tài dù", "attitude", "sikap"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["佚名", "yì míng", "Anonymous", "Tanpa Nama"],
    ["《", "", "", ""],
    ["尘埃", "chén āi", "Dust", "Habuk"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
